<a href="https://colab.research.google.com/github/adrian189gt/adrian189gt/blob/main/Copia_de_Copia_de_Untitled8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install --target=$nb_path nacal
from nacal import *

In [ ]:
A = Matrix([[1,0,0,0],[2,0,0,0],[0,3,3,3],[0,3,4,1],[0,1,2,1]])
A

$\left[ \begin{array}{cccc}1&0&0&0\\2&0&0&0\\0&3&3&3\\0&3&4&1\\0&1&2&1\\ \end{array} \right]$

In [ ]:
A|1

$\begin{pmatrix}1\\ 2\\ 0\\ 0\\ 0\end{pmatrix}$

In [ ]:
A|2

$\begin{pmatrix}0\\ 0\\ 3\\ 3\\ 1\end{pmatrix}$

In [ ]:
1|A

$\begin{pmatrix}1,& 0,& 0,& 0,\end{pmatrix}$

In [ ]:
b = A|1
c = A|2
d = A|3
e = A|4

In [ ]:
A = b*(-3) + c*(2) + d*(3) + e*(-3)
A

$\begin{pmatrix}3\\ 6\\ 24\\ 21\\ 11\end{pmatrix}$

$\begin{pmatrix}1,& 0,& 0,& 0,\end{pmatrix}$

In [ ]:
A = Matrix(([[1,0,0],[0,3,0],[0,0,-9]]))
A

$\left[ \begin{array}{ccc}1&0&0\\0&3&0\\0&0&-9\\ \end{array} \right]$

In [ ]:
A = Matrix(([[3,0,-4],[0,2,6],[-4,6,1]]))
A = Matrix(([[3,0,-4],[0,2,6],[-4,6,1]]))
A

$\left[ \begin{array}{ccc}3&0&-4\\0&2&6\\-4&6&1\\ \end{array} \right]$


In [ ]:
C = Matrix([[7,9,9],[2,3,9],[0,5,0]])
C

$\left[ \begin{array}{ccc}7&9&9\\2&3&9\\0&5&0\\ \end{array} \right]$

In [ ]:
C = Matrix([[7,9,9],[2,3,9],[0,5,0]])
A_transpuesta = ([[7,9,9],[2,3,9],[0,5,0]])
b = A - C + C
b

$\left[ \begin{array}{ccc}3&0&-4\\0&2&6\\-4&6&1\\ \end{array} \right]$

In [ ]:
!pip install --target=$nb_path nacal
from nacal import *

In [ ]:
A = Matrix([[7,9,9],[2,3,9]])


In [ ]:
b = Vector([7,6,3],[2,3,5])

In [ ]:
c = Vector([7,7,9],[2,9,1])

In [ ]:
t = A*(b + c)
t

$\begin{pmatrix}323\\ 175\end{pmatrix}$

In [ ]:
e = A*b + A*c
e

$\begin{pmatrix}323\\ 175\end{pmatrix}$

In [ ]:
!pip install --target=$nb_path nacal
from nacal import *

In [ ]:
lmbda=7

In [ ]:
import numpy as np


In [ ]:
A = np.array(([1,9],[7,7]))

In [ ]:
b = np.array([1,9])

In [ ]:
izquierda = A.dot(lmbda*b)

In [ ]:
derecha =  lmbda * A.dot(b)


In [ ]:
if np.array_equal(izquierda, derecha):
    print("La propiedad A(λb) = λ(Ab) se cumple.")
    print("Resultado izquierdo:", izquierda)
    print("Resultado derecho:", derecha)
else:
    print("La propiedad A(λb) = λ(Ab) no se cumple.")
    print("Resultado izquierdo:", izquierda)
    print("Resultado derecho:", derecha)

La propiedad A(λb) = λ(Ab) se cumple.
Resultado izquierdo: 574
Resultado derecho: 574


In [ ]:
import numpy as np

In [ ]:
A = np.array(([1,9],[7,7]))

In [ ]:
b = np.array([1,9])

In [ ]:
resultado_sin_parentesis = lmbda * A.dot(b)


In [ ]:
resultado_con_parentesis = (lmbda * A).dot(b)

In [ ]:
if np.array_equal(resultado_sin_parentesis, resultado_con_parentesis):
    print("En el caso λAb no son necesarios los paréntesis.")
    print("Resultado sin paréntesis:", resultado_sin_parentesis)
    print("Resultado con paréntesis:", resultado_con_parentesis)
else:
    print("En el caso λAb son necesarios los paréntesis.")
    print("Resultado sin paréntesis:", resultado_sin_parentesis)
    print("Resultado con paréntesis:", resultado_con_parentesis)

En el caso λAb no son necesarios los paréntesis.
Resultado sin paréntesis: 574
Resultado con paréntesis: 574


In [ ]:
!pip install --target=$nb_path nacal
from nacal import *

In [ ]:
import numpy as np


In [ ]:
import numpy as np

# Definir las dimensiones de la matriz B
num_filas = 3
num_columnas = 3

# Generar una matriz B del mismo orden que A con valores aleatorios
B = np.random.randint(1, 10, size=(num_filas, num_columnas))

# Mostrar la matriz B
print("Matriz B:")
print(B)


Matriz B:
[[1 3 5]
 [1 2 8]
 [7 7 4]]


In [ ]:
import numpy as np

# Definir la matriz A, la matriz B y el vector c
A = np.array([[1, 2, 3],
              [7, 10, 6],
              [7, 8, 9]])

B = np.array([[1, 3, 5],
              [1, 2, 8],
              [7, 7, 4]])

c = np.array([2, 3, 4])

In [ ]:
izquierda = (A + B).dot(c)

In [ ]:
derecha = A.dot(c) + B.dot(c)

In [ ]:
if np.array_equal(izquierda, derecha):
    print("La propiedad (A+B)c = Ac + Bc se cumple.")
    print("Resultado izquierdo:", izquierda)
    print("Resultado derecho:", derecha)
else:
    print("La propiedad (A+B)c = Ac + Bc no se cumple.")
    print("Resultado izquierdo:", izquierda)
    print("Resultado derecho:", derecha)

La propiedad (A+B)c = Ac + Bc se cumple.
Resultado izquierdo: [ 51 108 125]
Resultado derecho: [ 51 108 125]


In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[1, 3, 5],
              [1, 2, 8],
              [7, 7, 4]])

c = np.array([2, 3, 4])


parte_izquierda_sin_parentesis = (A + B).dot(c)

print("Parte izquierda de la ecuación sin paréntesis adicionales:")
print(parte_izquierda_sin_parentesis)

Parte izquierda de la ecuación sin paréntesis adicionales:
[ 51  87 125]


In [ ]:
import numpy as np


A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[1, 3, 5],
              [1, 2, 8],
              [7, 7, 4]])


In [ ]:
parte_izquierda = (A + B).T

In [ ]:
parte_derecha = A.T + B.T
if np.array_equal(parte_izquierda, parte_derecha):
    print("La propiedad (A + B)^T = A^T + B^T se cumple.")
    print("Resultado izquierdo:", parte_izquierda)
    print("Resultado derecho:", parte_derecha)
else:
    print("La propiedad (A + B)^T = A^T + B^T no se cumple.")
    print("Resultado izquierdo:", parte_izquierda)
    print("Resultado derecho:", parte_derecha)

La propiedad (A + B)^T = A^T + B^T se cumple.
Resultado izquierdo: [[ 2  5 14]
 [ 5  7 15]
 [ 8 14 13]]
Resultado derecho: [[ 2  5 14]
 [ 5  7 15]
 [ 8 14 13]]


In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[1, 3, 5],
              [1, 2, 8],
              [7, 7, 4]])

parte_izquierda_sin_parentesis = (A + B).T

parte_derecha_sin_parentesis = A.T + B.T

if np.array_equal(parte_izquierda_sin_parentesis, parte_derecha_sin_parentesis):
    print("No son necesarios paréntesis adicionales para ambos lados de la ecuación.")
    print("Resultado izquierdo:", parte_izquierda_sin_parentesis)
    print("Resultado derecho:", parte_derecha_sin_parentesis)
else:
    print("Los paréntesis adicionales son necesarios para al menos uno de los lados de la ecuación.")
    print("Resultado izquierdo:", parte_izquierda_sin_parentesis)
    print("Resultado derecho:", parte_derecha_sin_parentesis)


No son necesarios paréntesis adicionales para ambos lados de la ecuación.
Resultado izquierdo: [[ 2  5 14]
 [ 5  7 15]
 [ 8 14 13]]
Resultado derecho: [[ 2  5 14]
 [ 5  7 15]
 [ 8 14 13]]


In [ ]:

lmbda = 7

A = np.array(([1,9],[7,7]))

In [ ]:
lado_izquierdo = (lmbda * A).T

In [ ]:
lado_derecho = lmbda * A.T
if np.array_equal(lado_izquierdo, lado_derecho):
    print("La propiedad (λA)^T = λ(A^T) se cumple.")
    print("Resultado izquierdo:", lado_izquierdo)
    print("Resultado derecho:", lado_derecho)
else:
    print("La propiedad (λA)^T = λ(A^T) no se cumple.")
    print("Resultado izquierdo:", lado_izquierdo)
    print("Resultado derecho:", lado_derecho)

La propiedad (λA)^T = λ(A^T) se cumple.
Resultado izquierdo: [[ 7 49]
 [63 49]]
Resultado derecho: [[ 7 49]
 [63 49]]
